[package]
name = "deloop_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.28.1", features = ["persistence"] }
egui = { version = "0.28.1" }
env_logger = "0.11.5"
libc = "0.2.158"
serde = "1.0.210"
serde_json = "1.0.128"

[build-dependencies]
bindgen = "0.70.1"
cc = "1.1.15"
pkg-config = "0.3.30"
