# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tlog.proto\"\xae\x01\n\x08LogEntry\x12\x18\n\x05level\x18\x01 \x01(\x0e\x32\t.LogLevel\x12\x0c\n\x04tick\x18\x02 \x01(\r\x12\n\n\x02id\x18\x03 \x01(\r\x12\x11\n\x04\x61rg1\x18\x04 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04\x61rg2\x18\x05 \x01(\rH\x01\x88\x01\x01\x12\x11\n\x04\x61rg3\x18\x06 \x01(\rH\x02\x88\x01\x01\x12\x11\n\x04\x61rg4\x18\x07 \x01(\rH\x03\x88\x01\x01\x42\x07\n\x05_arg1B\x07\n\x05_arg2B\x07\n\x05_arg3B\x07\n\x05_arg4*R\n\x08LogLevel\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x44\x45\x42UG\x10\x01\x12\x08\n\x04INFO\x10\x02\x12\x0b\n\x07WARNING\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x12\x0c\n\x08\x43RITICAL\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGLEVEL']._serialized_start=190
  _globals['_LOGLEVEL']._serialized_end=272
  _globals['_LOGENTRY']._serialized_start=14
  _globals['_LOGENTRY']._serialized_end=188
# @@protoc_insertion_point(module_scope)
