# Project Name
TARGET = Template

# Sources
# C_INCLUDES = -I.

CPP_SOURCES = main.cpp \
  GC9A01.cpp

# Library Locations
LIBDAISY_DIR = external/libDaisy
# DAISYSP_DIR = @DAISYSP_DIR@

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
